#!/usr/bin/env node

// Copyright 2014 Technical Machine, Inc. See the COPYRIGHT
// file at the top-level directory of this distribution.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

var fs = require('fs');

function usage () {
  console.error("Usage: tessel-dfu-tool <read|write|run_bl|run_ram> <file>");
  process.exit(1);
}

var tessel_dfu = require('./tessel-dfu');
require('../src/commands');

var op = process.argv[2];
var file = process.argv[3];

if (!file) {
  usage();
}

if (op === "run_bl") {
	tessel_dfu.runNXP(file);
} else if (op === "read") {
	tessel_dfu.read(file);
} else if (op === "write") {
	tessel_dfu.write(fs.readFileSync(file));
} else if (op === "run_ram") {
	tessel_dfu.runRam(fs.readFileSync(file));
} else {
	usage();
}
