#!/usr/bin/env node

function usage () {
  console.error("Usage: ./tessel-restore <file>");
  process.exit(1);
}

var file = process.argv[2];
if (!file) {
  usage();
}

require('./tessel-dfu').flashTessel(file)