#!/usr/bin/env node

var fs = require('fs');

function usage () {
  console.error("Usage: tessel-dfu-tool <read|write|run_bl|run_ram> <file>");
  process.exit(1);
}

var tessel_dfu = require('./tessel-dfu');

var op = process.argv[2];
var file = process.argv[3];

if (!file) {
  usage();
}

if (op === "run_bl") {
	tessel_dfu.runNXP(file);
} else if (op === "read") {
	tessel_dfu.read(file);
} else if (op === "write") {
	tessel_dfu.write(fs.readFileSync(file));
} else if (op === "run_ram") {
	tessel_dfu.runRam(fs.readFileSync(file));
} else {
	usage();
}
